### ISSUE TITLE
keypad driver lost wakeup feature

### ISSUE THREAD

**Issue by junwushi** [OpenNuvoton/NUC970_Linux_Kernel#20]
please add pm feature in new keypad driver and enable wakeup by keypad

**Comment by junwushi** [comment]
and found rtc alarm wakeup feature also not working?

**Comment by yachen** [comment]
Hi @junwushi ,

New KPI driver can wake up system using GPIO interrupt.
We have customers using RTC alarm wake up without problem. And that part of code haven't been changed for a while. Have you tested suspend/resume feature with earlier kernel version? I'd like to know if this is caused by recent kernel update or not. 

Sincerely,

Yi-An Chen

**Comment by junwushi** [comment]
maybe others caused this issue.
